// packages/react/src/ActiveFrame.tsx
import {
  type CanvasHTMLAttributes,
  type Ref,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';
import {
  ActiveFrame as ActiveFrameCore,
  drawFrame,
  type ActiveFrameManifest,
  type FrameFit,
} from '@numbered/activeframe';

export interface ActiveFrameHandle {
  setFrame(n: number): void;
  getCurrentFrame(): number | null;
  getManifest(): ActiveFrameManifest | null;
}

export interface ActiveFrameProps extends Omit<CanvasHTMLAttributes<HTMLCanvasElement>, 'ref' | 'onError'> {
  src: string;
  fit?: FrameFit;
  hardwareAcceleration?: HardwareAcceleration;
  onReady?: (manifest: ActiveFrameManifest) => void;
  onError?: (err: Error) => void;
  ref?: Ref<ActiveFrameHandle | null>;
}

export default function ActiveFrame({
  src,
  fit = 'cover',
  hardwareAcceleration = 'prefer-hardware',
  onReady,
  onError,
  ref,
  ...canvasProps
}: ActiveFrameProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const instanceRef = useRef<ActiveFrameCore | null>(null);
  const fitRef = useRef<FrameFit>(fit);
  fitRef.current = fit;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const af = new ActiveFrameCore(src, {
      hardwareAcceleration,
      process: (frame) => drawFrame(frame, ctx, fitRef.current),
    });
    instanceRef.current = af;

    af.loading
      .then(() => onReady?.(af.manifest!))
      .catch((err: unknown) => onError?.(err instanceof Error ? err : new Error(String(err))));

    return () => {
      af.destroy();
      instanceRef.current = null;
    };
  }, [src, hardwareAcceleration]);

  useImperativeHandle(ref, () => ({
    setFrame: (n) => instanceRef.current?.setFrame(n),
    getCurrentFrame: () => instanceRef.current?.frame ?? null,
    getManifest: () => instanceRef.current?.manifest ?? null,
  }), []);

  return <canvas ref={canvasRef} {...canvasProps} />;
}

// packages/vue/src/ActiveFrame.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import {
  ActiveFrame as ActiveFrameCore,
  drawFrame,
  type ActiveFrameManifest,
  type FrameFit,
} from '@numbered/activeframe';

const props = withDefaults(
  defineProps<{
    src: string;
    fit?: FrameFit;
    hardwareAcceleration?: HardwareAcceleration;
  }>(),
  { fit: 'cover', hardwareAcceleration: 'prefer-hardware' },
);

const emit = defineEmits<{
  ready: [manifest: ActiveFrameManifest];
  error: [err: Error];
}>();

const canvas = ref<HTMLCanvasElement | null>(null);
let instance: ActiveFrameCore | null = null;

onMounted(() => {
  if (!canvas.value) return;
  const ctx = canvas.value.getContext('2d');
  if (!ctx) return;

  instance = new ActiveFrameCore(props.src, {
    hardwareAcceleration: props.hardwareAcceleration,
    process: (frame) => drawFrame(frame, ctx, props.fit),
  });

  instance.loading
    .then(() => emit('ready', instance!.manifest!))
    .catch((err: unknown) => emit('error', err instanceof Error ? err : new Error(String(err))));
});

onBeforeUnmount(() => {
  instance?.destroy();
  instance = null;
});

defineExpose({
  setFrame: (n: number) => instance?.setFrame(n),
  getCurrentFrame: () => instance?.frame ?? null,
  getManifest: () => instance?.manifest ?? null,
});
</script>

<template>
  <canvas ref="canvas" />
</template>
